name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enables Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm install
      - name: Test Coverage
        run: pnpm vitest run --coverage
        env:
          VITE_ACG_ID: ${{ secrets.VITE_ACG_ID }}
          VITE_ACG_SECURITY_TOKEN: ${{ secrets.VITE_ACG_SECURITY_TOKEN }}
          VITE_ACG_TOKEN: ${{ secrets.VITE_ACG_TOKEN }}
          VITE_FCM_SENDER_ID: ${{ secrets.VITE_FCM_SENDER_ID }}
          VITE_FCM_SERVER_KEY: ${{ secrets.VITE_FCM_SERVER_KEY }}
          VITE_FCM_TOKEN: ${{ secrets.VITE_FCM_TOKEN }}
          VITE_FCM_TOKEN_2: ${{ secrets.VITE_FCM_TOKEN_2 }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_GOOGLE_SERVICE_ACCOUNT: ${{ secrets.VITE_GOOGLE_SERVICE_ACCOUNT }}
          VITE_VAPID_KEY: ${{ secrets.VITE_VAPID_KEY }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
